sudo: false

language: c

env:
  - GHCVER=8.0.1

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-8.0.1
      - cabal-install-1.24
      - libgmp-dev
      - wrk

install:
  - (mkdir -p $HOME/.local/bin && cd $HOME/.local/bin && wget https://zalora-public.s3.amazonaws.com/tinc && chmod +x tinc)
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.24/bin:$PATH
  - ghc --version
  - cabal --version
  - travis_retry cabal update
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config

script:
  - tinc && cabal configure --enable-tests && cabal build && cabal test
  #- (cd doc && tinc cabal configure --enable-tests && cabal build && cabal test)

cache:
  directories:
    - $HOME/.tinc/cache
